# Training Configuration
model:
  type: "rvc"  # or "sovits", "bark", "tortoise"
  
training:
  batch_size: 8
  learning_rate: 0.0001
  epochs: 100
  save_interval: 10
  
data:
  train_ratio: 0.8
  val_ratio: 0.2
  
hebrew:
  phoneme_model: "espeak-ng"
  text_normalization: true
